import type { ComponentType, ReactNode } from "react";
import { AlertTriangle, LockKeyhole, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { ApiError } from "@/api/client";
import { cn } from "@/lib/utils";

export function SectionHeader({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <div className="flex items-end justify-between gap-4"><div><h2 className="text-base font-semibold text-foreground">{title}</h2>{description ? <p className="mt-1 text-sm text-muted-foreground">{description}</p> : null}</div>{action}</div>; }
export function MetricCard({ label, value, hint, icon: Icon, accent = false }: { label: string; value: ReactNode; hint?: string; icon?: ComponentType<{ className?: string }>; accent?: boolean }) { return <div className={cn("metric-card group", accent && "metric-card-accent")}><div className="flex items-center justify-between"><span className="text-xs font-medium uppercase text-muted-foreground">{label}</span>{Icon ? <Icon className="size-4 text-muted-foreground transition-colors group-hover:text-primary" /> : null}</div><div className="mt-3 font-mono text-2xl font-semibold tabular-nums text-foreground">{value ?? "—"}</div>{hint ? <p className="mt-1 text-xs text-muted-foreground">{hint}</p> : null}</div>; }
export function ProgressBar({ value, className }: { value: number; className?: string }) { const safe = Math.max(0, Math.min(100, Number.isFinite(value) ? value : 0)); return <div className={cn("h-1.5 overflow-hidden rounded-full bg-secondary", className)}><div className="h-full rounded-full bg-primary transition-[width] duration-700" style={{ width: `${safe}%` }} /></div>; }
export function ScoreRing({ value, label = "Career Score", size = "large" }: { value: number; label?: string; size?: "large" | "small" }) { const safe = Math.max(0, Math.min(100, value || 0)); return <div className={cn("relative grid place-items-center rounded-full", size === "large" ? "size-52" : "size-32")} style={{ background: `conic-gradient(var(--primary) ${safe * 3.6}deg, var(--secondary) 0deg)` }}><div className="absolute inset-2 grid place-items-center rounded-full bg-card"><div className="text-center"><div className={cn("font-mono font-semibold tabular-nums", size === "large" ? "text-4xl" : "text-2xl")}>{safe}<span className="text-base text-muted-foreground">/100</span></div><div className="mt-1 text-xs font-medium uppercase text-muted-foreground">{label}</div></div></div></div>; }
export function LoadingGrid({ count = 4 }: { count?: number }) { return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: count }).map((_, i) => <div className="metric-card" key={i}><Skeleton className="h-3 w-24"/><Skeleton className="mt-4 h-8 w-16"/><Skeleton className="mt-3 h-2 w-full"/></div>)}</div>; }
export function EmptyState({ title, description }: { title: string; description?: string }) { return <div className="grid min-h-48 place-items-center rounded-lg border border-dashed border-border bg-muted/20 p-8 text-center"><div><p className="font-medium text-foreground">{title}</p>{description ? <p className="mt-1 text-sm text-muted-foreground">{description}</p> : null}</div></div>; }
export function ErrorState({ error, message, retry }: { error: unknown; message: string; retry: () => void }) { const auth = error instanceof ApiError && (error.kind === "unauthorized" || error.kind === "forbidden"); return <div className="grid min-h-44 place-items-center rounded-lg border border-border bg-card p-6 text-center"><div>{auth ? <LockKeyhole className="mx-auto size-5 text-warning"/> : <AlertTriangle className="mx-auto size-5 text-destructive"/>}<p className="mt-3 font-medium text-foreground">{auth ? error.message : message}</p><p className="mt-1 text-sm text-muted-foreground">{auth ? "Connect your backend login flow to continue." : "Other dashboard sections remain available."}</p><Button variant="outline" size="sm" className="mt-4" onClick={retry}><RefreshCw/>Retry</Button></div></div>; }
export function Panel({ children, className }: { children: ReactNode; className?: string }) { return <section className={cn("panel", className)}>{children}</section>; }
