import type { ReactNode } from "react";
import { useQuery, type UseQueryResult } from "@tanstack/react-query";
import { format, parseISO } from "date-fns";
import { Activity, ArrowUpRight, BookOpenCheck, CheckCircle2, CircleDot, Clock3, Code2, Flame, FolderGit2, GitCommit, Github, GitFork, Layers3, Star, Target, Trophy, Wrench } from "lucide-react";
import { dsaQuery, careerQuery, githubActivityQuery, githubAnalyticsQuery, leetcodeQuery, projectsQuery, skillEvidenceQuery, skillsQuery } from "@/api/queries";
import type { Project, ProjectStatus } from "@/api/types";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { ContributionHeatmap } from "./contribution-heatmap";
import { DifficultyChart, LanguageChart, ScoreComparison } from "./charts";
import { EvidenceList } from "./evidence-list";
import { EmptyState, ErrorState, LoadingGrid, MetricCard, Panel, ProgressBar, ScoreRing, SectionHeader } from "./data-ui";

function PageIntro({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <header className="mb-7"><p className="eyebrow">{eyebrow}</p><h1 className="mt-2 text-2xl font-semibold text-foreground sm:text-3xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p></header>; }
function QueryBlock<T>({ query, loading = 4, message, children }: { query: UseQueryResult<T, Error>; loading?: number; message: string; children: (data: T) => ReactNode }) { if (query.isLoading) return <LoadingGrid count={loading}/>; if (query.error || query.data === undefined) return <ErrorState error={query.error} message={message} retry={() => void query.refetch()}/>; return children(query.data); }
const fmt = (n: number | null | undefined) => n == null ? "—" : n.toLocaleString();

export function DashboardPage() {
 const career = useQuery(careerQuery), dsa = useQuery(dsaQuery), leetcode = useQuery(leetcodeQuery), gh = useQuery(githubAnalyticsQuery), activity = useQuery(githubActivityQuery);
 return <div className="page-wrap"><PageIntro eyebrow="Overview" title="Developer Career Command Center" description="Track your coding progress, technical skills, projects and developer activity in one place."/>
 <QueryBlock query={career} message="Unable to load career analytics.">{(data) => <><Panel className="score-hero"><div className="score-copy"><p className="eyebrow">Career readiness</p><h2 className="mt-3 text-xl font-semibold">One score. Every signal.</h2><p className="mt-2 max-w-lg text-sm leading-6 text-muted-foreground">Calculated by your backend from DSA, skills, projects, GitHub activity and consistency.</p></div><ScoreRing value={data.careerScore}/><div className="score-metrics">{[{n:"DSA",v:data.dsaScore},{n:"Skills",v:data.skillsScore},{n:"Projects",v:data.projectsScore},{n:"GitHub",v:data.githubScore},{n:"Consistency",v:data.consistencyScore}].map(x=><div key={x.n}><div className="flex justify-between text-xs"><span className="text-muted-foreground">{x.n}</span><span className="font-mono">{x.v}</span></div><ProgressBar value={x.v} className="mt-2"/></div>)}</div></Panel>
 <div className="mt-5 grid gap-5 lg:grid-cols-2"><Panel><SectionHeader title="Skills snapshot" description="Current breadth and average evidence strength"/><div className="mt-5 grid grid-cols-2 gap-3"><MetricCard label="Total skills" value={data.skills.totalSkills} icon={Layers3}/><MetricCard label="Avg. strength" value={`${data.skills.averageStrength}%`} icon={Target}/></div></Panel><Panel><SectionHeader title="Project snapshot" description="Portfolio delivery status"/><div className="mt-5 grid grid-cols-3 gap-3"><MetricCard label="Total" value={data.projects.totalProjects}/><MetricCard label="Complete" value={data.projects.completedProjects}/><MetricCard label="In progress" value={data.projects.inProgressProjects}/></div></Panel></div></> }</QueryBlock>
 <div className="mt-5 grid gap-5 xl:grid-cols-2"><Panel><SectionHeader title="DSA snapshot" description="DevTrack and LeetCode are tracked separately"/><div className="mt-5"><QueryBlock query={dsa} loading={3} message="Unable to load DevTrack DSA stats.">{(x)=><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><MetricCard label="DevTrack solved" value={x.totalSolved}/><MetricCard label="Current streak" value={x.currentStreak}/><MetricCard label="Longest streak" value={x.longestStreak}/></div>}</QueryBlock></div><div className="mt-3"><QueryBlock query={leetcode} loading={3} message="Unable to load LeetCode stats.">{(x)=><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><MetricCard label="LeetCode solved" value={x.totalSolved} accent/><MetricCard label="Easy" value={x.easySolved}/><MetricCard label="Medium" value={x.mediumSolved}/><MetricCard label="Hard" value={x.hardSolved}/></div>}</QueryBlock></div></Panel>
 <Panel><SectionHeader title="GitHub snapshot" description="Repository reach and contribution activity"/><div className="mt-5"><QueryBlock query={gh} loading={3} message="Unable to load GitHub analytics.">{(x)=><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><MetricCard label="Repositories" value={x.totalRepositories}/><MetricCard label="Original" value={x.originalRepositories}/><MetricCard label="Stars" value={x.totalStars}/><MetricCard label="Forks" value={x.totalForks}/></div>}</QueryBlock></div><div className="mt-3"><QueryBlock query={activity} loading={2} message="Unable to load GitHub activity.">{(x)=><div className="grid grid-cols-2 gap-3"><MetricCard label="Commits" value={x.totalCommits}/><MetricCard label="Active days" value={x.activeDays}/></div>}</QueryBlock></div></Panel></div>
 <Panel className="mt-5"><SectionHeader title="Recent activity" description="Contribution intensity from dates returned by GitHub"/><div className="mt-6"><QueryBlock query={activity} loading={3} message="Unable to load GitHub activity.">{(x)=><ContributionHeatmap commitsByDate={x.commitsByDate}/>}</QueryBlock></div></Panel></div>;
}

export function DsaPage() { const dsa=useQuery(dsaQuery), lc=useQuery(leetcodeQuery); return <div className="page-wrap"><PageIntro eyebrow="Practice intelligence" title="DSA Progress" description="See your DevTrack practice and LeetCode performance without mixing their totals."/><QueryBlock query={dsa} loading={6} message="Unable to load DevTrack DSA stats.">{(x)=><><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><MetricCard label="Total problems" value={x.totalProblems} icon={Code2}/><MetricCard label="Solved" value={x.totalSolved} icon={CheckCircle2}/><MetricCard label="Todo" value={x.totalTodo} icon={CircleDot}/><MetricCard label="In progress" value={x.totalInProgress} icon={Clock3}/><MetricCard label="Current streak" value={x.currentStreak} icon={Flame}/><MetricCard label="Longest streak" value={x.longestStreak} icon={Trophy}/></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><Panel><SectionHeader title="Difficulty distribution"/><div className="mt-4"><DifficultyChart {...x.difficultyBreakdown}/></div></Panel><Panel><SectionHeader title="Topic progress"/>{x.topicProgress.length ? <div className="mt-6 space-y-5">{x.topicProgress.map((t,i)=>{ const percent=t.progressPercentage ?? (t.totalProblems ? t.solvedProblems/t.totalProblems*100 : 0); return <div key={`${t.topic ?? t.topicName ?? t.name}-${i}`}><div className="flex justify-between text-sm"><span>{t.topic ?? t.topicName ?? t.name ?? "Topic"}</span><span className="font-mono text-muted-foreground">{t.solvedProblems}/{t.totalProblems}</span></div><ProgressBar value={percent} className="mt-2"/></div>})}</div>:<div className="mt-4"><EmptyState title="No topic progress yet."/></div>}</Panel></div><Panel className="mt-5"><SectionHeader title="Problems solved over time"/>{x.problemsSolvedOverTime.length ? <div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{x.problemsSolvedOverTime.map((p)=><MetricCard key={p.date} label={format(parseISO(p.date),"MMM d")} value={p.count ?? p.solved ?? p.problemsSolved ?? 0}/>)}</div>:<div className="mt-5"><EmptyState title="No DevTrack DSA activity yet"/></div>}</Panel></>}</QueryBlock>
 <Panel className="mt-5 leetcode-panel"><SectionHeader title="LeetCode" description="External problem-solving profile"/><div className="mt-5"><QueryBlock query={lc} loading={4} message="Unable to load LeetCode stats.">{(x)=><div className="grid gap-5 lg:grid-cols-[1fr_1.4fr]"><div className="grid grid-cols-2 gap-3"><MetricCard label="Total solved" value={x.totalSolved} accent/><MetricCard label="Ranking" value={fmt(x.ranking)}/><MetricCard label="Username" value={x.username ?? "—"}/></div><DifficultyChart easy={x.easySolved} medium={x.mediumSolved} hard={x.hardSolved}/></div>}</QueryBlock></div></Panel></div>; }

export function SkillsPage() { const skills=useQuery(skillsQuery), evidence=useQuery(skillEvidenceQuery), career=useQuery(careerQuery); return <div className="page-wrap"><PageIntro eyebrow="Technical profile" title="Skills" description="Your declared stack and the repository evidence that supports it."/><QueryBlock query={career} loading={2} message="Unable to load skill analytics.">{x=><div className="grid gap-3 sm:grid-cols-2"><MetricCard label="Total skills" value={x.skills.totalSkills} icon={Layers3}/><MetricCard label="Average strength" value={`${x.skills.averageStrength}%`} icon={Target}/></div>}</QueryBlock><Panel className="mt-5"><SectionHeader title="Skill inventory" description="Grouped by category"/><div className="mt-5"><QueryBlock query={skills} loading={4} message="Unable to load skills.">{items=>items.length?<div className="grid gap-4 lg:grid-cols-2">{Object.entries(items.reduce<Record<string,typeof items>>((a,s)=>{(a[s.category]??=[]).push(s);return a},{})).map(([category,list])=><div className="skill-group" key={category}><div className="flex items-center gap-2"><Wrench className="size-4 text-primary"/><h3 className="font-medium">{category.replaceAll("_"," ")}</h3><Badge variant="outline" className="ml-auto">{list.length}</Badge></div><div className="mt-4 flex flex-wrap gap-2">{list.map(skill=><span className="skill-chip" key={skill.id}>{skill.name}</span>)}</div></div>)}</div>:<EmptyState title="No skills added yet."/>}</QueryBlock></div></Panel><Panel className="mt-5"><SectionHeader title="Evidence & strength" description="Signals derived from your public repositories"/><div className="mt-5"><QueryBlock query={evidence} loading={5} message="Unable to load skill evidence.">{x=><EvidenceList items={x}/>}</QueryBlock></div></Panel></div>; }

const statusLabel:Record<ProjectStatus,string>={COMPLETED:"Completed",IN_PROGRESS:"In progress",PLANNED:"Planned",ARCHIVED:"Archived"};
function ProjectDetails({project}:{project:Project}) { return <Dialog><DialogTrigger asChild><Button variant="outline" size="sm">View details<ArrowUpRight/></Button></DialogTrigger><DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{project.name}</DialogTitle><DialogDescription>{project.description ?? "No description provided."}</DialogDescription></DialogHeader><div className="space-y-5">{[["Key features",project.keyFeatures],["Challenges",project.challenges],["Learnings",project.learnings],["Resume description",project.resumeDescription],["Interview notes",project.interviewNotes]].map(([l,v])=>v?<div key={l}><p className="text-xs font-medium uppercase text-muted-foreground">{l}</p><p className="mt-2 text-sm leading-6 text-foreground">{v}</p></div>:null)}</div></DialogContent></Dialog>; }
export function ProjectsPage() { const q=useQuery(projectsQuery); return <div className="page-wrap"><PageIntro eyebrow="Portfolio" title="Projects" description="A recruiter-ready view of what you built, the problems you solved, and the technologies you used."/><QueryBlock query={q} loading={6} message="Unable to load projects.">{items=>items.length?<div className="grid gap-4 lg:grid-cols-2">{items.map(p=><article className="project-card" key={p.id}><div className="flex items-start justify-between gap-3"><div className="grid size-10 place-items-center rounded-md bg-secondary text-primary"><FolderGit2 className="size-5"/></div><Badge className={`project-status status-${p.status.toLowerCase()}`} variant="outline">{statusLabel[p.status]}</Badge></div><h2 className="mt-5 text-lg font-semibold">{p.name}</h2><p className="mt-2 min-h-10 text-sm leading-5 text-muted-foreground">{p.description ?? "No description provided."}</p><div className="mt-4 flex flex-wrap gap-2">{p.skills.map(s=><span className="skill-chip" key={s.id}>{s.name}</span>)}</div><div className="mt-6 flex flex-wrap items-center gap-2"><ProjectDetails project={p}/>{p.githubUrl?<Button asChild variant="ghost" size="sm"><a href={p.githubUrl} target="_blank" rel="noreferrer"><Github/>GitHub</a></Button>:null}{p.liveUrl?<Button asChild variant="ghost" size="sm"><a href={p.liveUrl} target="_blank" rel="noreferrer"><ArrowUpRight/>Live</a></Button>:null}</div></article>)}</div>:<EmptyState title="No projects added yet."/>}</QueryBlock></div>; }

export function GithubPage() { const analytics=useQuery(githubAnalyticsQuery), activity=useQuery(githubActivityQuery), evidence=useQuery(skillEvidenceQuery); return <div className="page-wrap"><PageIntro eyebrow="Source intelligence" title="GitHub Analytics" description="Repository reach, language focus and a date-accurate view of contribution consistency."/><QueryBlock query={analytics} loading={6} message="Unable to load GitHub analytics.">{x=><><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><MetricCard label="Repositories" value={x.totalRepositories} icon={Github}/><MetricCard label="Original" value={x.originalRepositories} icon={BookOpenCheck}/><MetricCard label="Forked" value={x.forkedRepositories} icon={GitFork}/><MetricCard label="Stars" value={x.totalStars} icon={Star}/><MetricCard label="Forks" value={x.totalForks} icon={GitFork}/><MetricCard label="Top language" value={x.mostUsedLanguage ?? "—"} icon={Code2}/></div><Panel className="mt-5"><SectionHeader title="Language distribution" description="Repositories by primary language"/><div className="mt-4"><LanguageChart distribution={x.languageDistribution}/></div></Panel></>}</QueryBlock><Panel className="mt-5 activity-panel"><SectionHeader title="Contribution activity" description="Commit intensity across backend-provided dates"/><div className="mt-5"><QueryBlock query={activity} loading={4} message="Unable to load GitHub activity.">{x=><><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Total commits" value={x.totalCommits} icon={GitCommit}/><MetricCard label="Active days" value={x.activeDays} icon={Activity}/><MetricCard label="First activity" value={x.firstActivity ? format(parseISO(x.firstActivity),"MMM d, yyyy") : "—"}/><MetricCard label="Last activity" value={x.lastActivity ? format(parseISO(x.lastActivity),"MMM d, yyyy") : "—"}/></div><div className="mt-8"><ContributionHeatmap commitsByDate={x.commitsByDate}/></div></>}</QueryBlock></div></Panel><Panel className="mt-5"><SectionHeader title="GitHub skill evidence"/><div className="mt-5"><QueryBlock query={evidence} loading={5} message="Unable to load skill evidence.">{x=><EvidenceList items={x}/>}</QueryBlock></div></Panel></div>; }

export function CareerPage() { const q=useQuery(careerQuery); return <div className="page-wrap"><PageIntro eyebrow="Career intelligence" title="Career Analytics" description="A consolidated, backend-calculated view of your readiness across five developer signals."/><QueryBlock query={q} loading={5} message="Unable to load career analytics.">{x=><><Panel className="score-hero"><div><p className="eyebrow">Calculated metric</p><h2 className="mt-2 text-xl font-semibold">Career readiness score</h2><p className="mt-2 max-w-md text-sm leading-6 text-muted-foreground">This score comes directly from career analytics and is never generated in the frontend.</p></div><ScoreRing value={x.careerScore}/><div className="min-w-0 flex-1"><ScoreComparison data={[{name:"DSA",score:x.dsaScore},{name:"Skills",score:x.skillsScore},{name:"Projects",score:x.projectsScore},{name:"GitHub",score:x.githubScore},{name:"Consistency",score:x.consistencyScore}]}/></div></Panel><div className="mt-5 grid gap-5 lg:grid-cols-2"><Panel><SectionHeader title="DSA"/><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3"><MetricCard label="DevTrack solved" value={x.dsa.devTrackSolved}/><MetricCard label="LeetCode solved" value={x.dsa.leetCodeSolved}/><MetricCard label="Easy" value={x.dsa.easySolved}/><MetricCard label="Medium" value={x.dsa.mediumSolved}/><MetricCard label="Hard" value={x.dsa.hardSolved}/><MetricCard label="Current streak" value={x.dsa.currentStreak}/><MetricCard label="Longest streak" value={x.dsa.longestStreak}/></div></Panel><Panel><SectionHeader title="GitHub"/><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3"><MetricCard label="Repositories" value={x.github.repositories}/><MetricCard label="Original" value={x.github.originalRepositories}/><MetricCard label="Stars" value={x.github.totalStars}/><MetricCard label="Forks" value={x.github.totalForks}/><MetricCard label="Active days" value={x.github.activeDays}/><MetricCard label="Commits" value={x.github.totalCommits}/></div></Panel><Panel><SectionHeader title="Skills"/><div className="mt-5 grid grid-cols-2 gap-3"><MetricCard label="Total skills" value={x.skills.totalSkills}/><MetricCard label="Average strength" value={`${x.skills.averageStrength}%`}/></div></Panel><Panel><SectionHeader title="Projects"/><div className="mt-5 grid grid-cols-3 gap-3"><MetricCard label="Total" value={x.projects.totalProjects}/><MetricCard label="Completed" value={x.projects.completedProjects}/><MetricCard label="In progress" value={x.projects.inProgressProjects}/></div></Panel><Panel className="lg:col-span-2"><SectionHeader title="Consistency"/><div className="mt-5 grid gap-3 sm:grid-cols-3"><MetricCard label="DSA current streak" value={x.consistency.dsaCurrentStreak}/><MetricCard label="DSA longest streak" value={x.consistency.dsaLongestStreak}/><MetricCard label="GitHub active days" value={x.consistency.githubActiveDays}/></div></Panel></div></>}</QueryBlock></div>; }
