server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: devtrack-backend

  cache:
    caffeine:
      spec: maximumSize=500,expireAfterWrite=15m

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:devtracker}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  jackson:
    default-property-inclusion: non_null

devtrack:
  jwt:
    secret: ${JWT_SECRET:change-this-secret-in-prod-please-make-it-long-and-random-base64}
    access-token-expiration-ms: ${JWT_ACCESS_EXP_MS:3600000}      # 1 hour
    refresh-token-expiration-ms: ${JWT_REFRESH_EXP_MS:604800000} # 7 days
  github:
    api-base-url: ${GITHUB_API_BASE_URL:https://api.github.com}
    client-id: ${GITHUB_CLIENT_ID:}
    client-secret: ${GITHUB_CLIENT_SECRET:}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:8081,http://localhost:5173,http://localhost:3000}
logging:
  level:
    com.devtrack: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:WARN}
